# Generated by Django 5.0.1 on 2024-02-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupheader',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupheader',
            name='header',
        ),
        migrations.RemoveField(
            model_name='groupheader',
            name='insert_by',
        ),
        migrations.RemoveField(
            model_name='groupheader',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='headers',
            name='insert_by',
        ),
        migrations.RemoveField(
            model_name='headers',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='insert_by',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupHeader',
        ),
        migrations.DeleteModel(
            name='Headers',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
